<?php

namespace App\Cloud;

class CloudSubscriptionEventType
{
    const TRIAL_STARTED = 'TRIAL_STARTED';
    const TRIAL_EXTENDED = 'TRIAL_EXTENDED';
    const TRIAL_EXPIRED = 'TRIAL_EXPIRED';
    const SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED';
    const PAYMENT_REQUESTED = 'PAYMENT_REQUESTED';
    const PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED';
    const PAYMENT_FAILED = 'PAYMENT_FAILED';
    const PAYMENT_RECONCILE = 'PAYMENT_RECONCILE';
    const SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED';
    const SUBSCRIPTION_RENEWED = 'SUBSCRIPTION_RENEWED';
    const PAST_DUE = 'PAST_DUE';
    const SUSPENDED = 'SUSPENDED';
    const CANCELLED = 'CANCELLED';
    const EXPIRED = 'EXPIRED';
    const ADMIN_OVERRIDE = 'ADMIN_OVERRIDE';
}
